CRM/Sqltasks/Action.php
CRM/Sqltasks/Action/APICall.php
CRM/Sqltasks/Action/CSVExport.php
CRM/Sqltasks/Action/CreateActivity.php
CRM/Sqltasks/Action/SegmentationAssign.php
CRM/Sqltasks/Action/SyncGroup.php
CRM/Sqltasks/Action/SyncTag.php

This adds support for an "exclude" column in data tables. When the column is present in a table and the value is 1, the row is skipped within the action. For the SegmentationAssign action, affected rows are added to the exclusion test table.
Fixes #22

Add exclude column for data tables

---

CRM/Sqltasks/Action/ResultHandler.php
CRM/Sqltasks/Action/SegmentationExport.php

Skip the success handler if the SegmentationExport action exported an empty file.
The empty (header-only) file is still exported to preserve backwards-compatibility.

Don't set executed if exported segments are empty

---

CRM/Sqltasks/Action/SegmentationAssign.php

Fixes a syntax error when a `membership_id` column is present in the data table.

GP-1813: Fix query in SegmentationAssign action

---

CRM/Sqltasks/Action/CreateActivity.php

We don't want to create empty mass activities whenever a task with an empty contact table is executed.

GP-1483: Don't create activity if contact table is empty

---

CRM/Sqltasks/Page/Manager.php

Certain characters like double quotes can cause exports to fail because of an invalid HTTP header. This filters out all characters that are potentially problematic in file names.
Fixes #31

Sanitize file name when exporting job

---

CRM/Sqltasks/Action/CreateActivity.php
CRM/Sqltasks/Action/SegmentationAssign.php
CRM/Sqltasks/Action/SegmentationExport.php
templates/CRM/Sqltasks/Action/CreateActivity.tpl
templates/CRM/Sqltasks/Action/SegmentationExport.tpl
templates/CRM/Sqltasks/Page/Runner.tpl

In order to keep track of contacts in exclusion segments, this change creates an activity of type "Exclusion Record" when there's a matching row in civicrm_segmentation_exclude.
This also includes minor improvements to the "Create Activity" and "Segmentation Export" action:
- For "Create Activity", all contact fields now use an entityRef form element, and the "Campaign" field allows filtering. Additionally, a number of missing fields like medium and source_record_id were added.
- For "Segmentation Export", a "Discard empty file?" option was added. This option is triggered if no contacts are found in the selected campaign/segment.
Related to https://github.com/systopia/de.systopia.segmentation/pull/12

GP-1940: Track exclusions via activity, other improvements

---

CRM/Sqltasks/Action/APICall.php
CRM/Sqltasks/Action/CSVExport.php
CRM/Sqltasks/Action/ContactSet.php
CRM/Sqltasks/Action/CreateActivity.php
CRM/Sqltasks/Action/ResultHandler.php
CRM/Sqltasks/Form/Configure.php
templates/CRM/Sqltasks/Action/CreateActivity.tpl
templates/CRM/Sqltasks/Form/Configure.tpl

This changes all input fields dealing with code, tokens or similar to use a monospace font.
It also includes minor style improvements, including changes to textarea sizes and a spacing fix for shoreditch.

Use monospace font for code, style improvements

---

js/sortTasks.js

This changes the task overview drag-and-drop sorter (implemented via the jQuery UI Sortable widget) to lazily initialize the sorter for each row on mouseenter. This dramatically improves loading speed on installations with a large number of tasks.
Fixes #39

Use lazy initialization for task overview sorter

---

CRM/Sqltasks/Action/SyncGroup.php
CRM/Sqltasks/Action/SyncTag.php

This fixes various scenarios where tag or group sync can cause duplicate key errors, including cases where the data table contains duplicate contact IDs and where tag/group membership is changed
concurrently.
Error handling for duplicate keys is now performed via `ON DUPLICATE KEY` rather than `INSERT IGNORE` because the latter could potentially ignore other, unrelated database errors.
GP-1735

Fix duplicate key error during group or tag sync

---

templates/CRM/Sqltasks/Page/Manager.tpl

This fixes two shoreditch styling issues:
- Disabled tasks were not visually distinguishable from enabled ones
- The action menu was using markup that's incompatible with shoreditch
Fixes #45

Fix shoreditch styling issues

---

CRM/Sqltasks/Action/CSVExport.php

~When Exporting CSV, the `path` variable is incorrect~, and in case it's empty it doesn't add any default directory

add default dir when csv_path is empty

---

CRM/Sqltasks/Action/CSVExport.php
sqltasks.php
templates/CRM/Sqltasks/Action/CSVExport.hlp
templates/CRM/Sqltasks/Action/CSVExport.tpl

Even if the csv file is too big or for security reasons, sometimes is not a good idea to attach a csv file with raw information from CiviCRM DB.
This PR adds a setting to allows a new token in the template email, that will be replaced by an URL to click and download the csv/zip file, through CiviCRM authentication

add downloadURL token in csv export task

---

CRM/Sqltasks/Task.php
api/v3/Sqltask.php

This adds a new parameter `log_to_file` to `Sqltask.execute`. If set, logs generated during task execution are written to a dedicated log file. The flag also determines whether logs are returned by the API, making it possible to prevent issues with long log values not fitting
in `civicrm_job_log.data` during scheduled execution.
This also includes some minor UX/DX improvements in log output.
Fixes #60

Add "log_to_file" parameter for Sqltask.execute

---

CRM/Sqltasks/Task.php

When using token `{sqltasks.downloadURL}` in email templates, the download link url must be absolute to access the file when clicking. This work as well when downloading it from CiviCRM UI

set abosolute url for download_link

---

CRM/Sqltasks/Action.php
CRM/Sqltasks/Action/CreateActivity.php
CRM/Sqltasks/Task.php
CRM/Sqltasks/Utils.php
phpunit.xml.dist
tests/fixtures/csvexport.csv
tests/phpunit/CRM/Sqltasks/Action/APICallTest.php
tests/phpunit/CRM/Sqltasks/Action/AbstractActionTest.php
tests/phpunit/CRM/Sqltasks/Action/CSVExportTest.php
tests/phpunit/CRM/Sqltasks/Action/CreateActivityTest.php
tests/phpunit/CRM/Sqltasks/Action/ResultHandlerTest.php
tests/phpunit/CRM/Sqltasks/Action/SegmentationAssignTest.php
tests/phpunit/CRM/Sqltasks/Action/SegmentationExportTest.php
tests/phpunit/CRM/Sqltasks/Action/SyncGroupTest.php
tests/phpunit/CRM/Sqltasks/Action/SyncTagTest.php
tests/phpunit/bootstrap.php

This adds basic unit tests for existing SQL task actions. This is in preparation for changes to the configuration format to allow actions to be used more flexibly (i.e. using the same action multiple times within the same task, reordering actions). Since this will require major changes, we want to make sure to not break existing functionality.

Add unit tests

---

sqltasks.php

Check if  `sqltasks` tokens are coming in `hook_civicrm_tokenValues()`, to avoid executing following code for ANY token in EVERY action involving tokens in Civi

check if sqltasks tokens are included to execute code

---

CRM/Sqltasks/Action/CSVExport.php
CRM/Sqltasks/Action/EmailActionTrait.php
CRM/Sqltasks/Action/ResultHandler.php
CRM/Sqltasks/Action/SegmentationExport.php

This fixes an issue with newer versions of Civi when sending emails to multiple recipients using a comma-separated list of email addresses.
`MessageTemplate.send` no longer accepts multiple recipients in a single call, so we call the API multiple times instead.
Shared email sending code was extracted into a trait to DRY things up a bit.

GP-26375 Fix email issue when sending to multiple recipients

---

composer.json

add composer.json with package name, so this extension can be easily included in main D8/D9 composer stack file.
Discussion in MM extension channel [here](https://chat.civicrm.org/civicrm/pl/kqhekzi3a3rz7bscgjemf6afjh)

add composer.json to facilitate inclusion in Drupal 9 stack with composer

---

CRM/Sqltasks/Config/Format.php
tests/phpunit/CRM/Sqltasks/Config/FormatTest.php

This fixes an issue where tasks using the `##### SQLTASK VERSION 0.9 ###########` format are only partially imported.
Fixes #108

Fix import of legacy tasks ("VERSION 0.9" format)

---

api/v3/Sqltask/Execute.php
api/v3/Sqltaskfield/Getmessagetemplates.php

Just suppressing some PHP8 warnings.

fix undefined array key warnings in PHP8

---

Civi/Sqltasks/CompilerPass.php

Fix TypeError: Symfony\Component\DependencyInjection\Definition::addMethodCall(): Argument #3 ($returnsClone) must be of type bool, array given
